export const MAIN_BUTTON_DIAMETER = 200;
export const SMALL_BUTTON_DIAMETER = 120;
export const PLAYVIEW_HEADER_TOP_PADDING = 40;
export const PLAYVIEW_CHALLENGER_HEIGHT = 30;
export const PLAYVIEW_OTHERS_HEIGHT = 20;
export const PLAYVIEW_TIMER_HEIGHT = 50;
export const RESULT_TIME_WIDTH = 85;
export const TOP_ICON_OFFSET = 40;
export const SIDE_ICON_OFFSET = 20;
export const RESULT_ICON_SIZE = 40;
export const PLAY_BUTTON_TOP_MARGIN = 100;
export const PLAYVIEW_HEADER_HEIGHT = PLAYVIEW_HEADER_TOP_PADDING + PLAYVIEW_CHALLENGER_HEIGHT + PLAYVIEW_OTHERS_HEIGHT + PLAYVIEW_TIMER_HEIGHT;
export const MAIN_FONT_STYLE = 'TextMeOne_400Regular';

export const PRIMARY_COLOR = '#CF0000';
export const SECONDARY_COLOR = '#d6c5b0';
export const ACCENT_COLOR = '#523429';

export const GOLD = '#D1B000';
export const SILVER = '#C0C0C0';
export const BRONZE = '#a44728';
